-- Table: customer
CREATE TABLE customer (
                          id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          first_name VARCHAR(20) NOT NULL,
                          last_name VARCHAR(20) NOT NULL
);

-- Table: exercise
CREATE TABLE exercise (
                          id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          exercise_name VARCHAR(20) NOT NULL,
                          muscle_group VARCHAR(20) NOT NULL
);

-- Table: workout
CREATE TABLE workout (
                         id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         customer_id INT NOT NULL,
                         "date" DATE NOT NULL,
                         exercise_id INT NOT NULL,
                         sets INT NOT NULL,
                         reps INT NOT NULL,
                         weight DECIMAL(10,2) NOT NULL,
                         CONSTRAINT workout_customer_fk FOREIGN KEY (customer_id) REFERENCES customer(id),
                         CONSTRAINT workout_exercise_fk FOREIGN KEY (exercise_id) REFERENCES exercise(id)
);